name 'stbenjam-ipaclient'
version '2.3.0'
author 'stbenjam'
license 'MIT'
summary 'Manages server IPA Registration'
description 'A Puppet module for managing FreeIPA Client Registration'
project_page 'http://www.github.com/stbenjam/puppet-ipaclient'
source 'http://www.github.com/stbenjam/puppet-ipaclient'

dependency 'puppetlabs/stdlib', '>= 3.0.0'
