name 'stbenjam-ipaclient'
version '0.9.0'
author 'stbenjam'
license 'MIT'
summary 'Manages server IPA Registration'
description 'A Puppet module for managing FreeIPA Client Registration'
project_page 'http://www.github.com/stbenjam/puppet-ipaclient'
