name    'stbenjam-ipaclient'
version '0.5.0'
author 'stbenjam'
license 'MIT'
summary 'Manages server IPA Registration'
description 'A Puppet module for managing Red Hat IPA Registration'
project_page 'http://www.github.com/stbenjam/puppet-ipaclient'
